apiVersion: v1
kind: Service
metadata:
  name: alex-pairing
  annotations:
    "lbipam.cilium.io/sharing-key": "per-user-alex"
spec:
  selector:
    app: direwolf
  ports:
  - name: https
    port: 47984
    protocol: TCP
  - name: http
    port: 47989
    protocol: TCP
  type: LoadBalancer
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: alex-rtp
#   annotations:
#     "lbipam.cilium.io/sharing-key": "per-user-alex"
# spec:
#   selector:
#     direwolf-user: alex
#   ports:
#   - name: control
#     port: 47999
#     protocol: UDP
#   - port: 47998
#     protocol: UDP
#     name: rtp-video
#   - port: 48000
#     protocol: UDP
#     name: rtp-audio
#   - name: rtsp
#     port: 48010
#   - name: rtsp-udp-0
#     port: 48100
#     protocol: UDP
#   - name: rtsp-udp-1
#     port: 48101
#     protocol: UDP
#   - name: rtsp-udp-2
#     port: 48102
#     protocol: UDP
#   - name: rtsp-udp-3
#     port: 48103
#     protocol: UDP
#   - name: rtsp-udp-4
#     port: 48104
#     protocol: UDP
#   - name: rtsp-udp-5
#     port: 48105
#     protocol: UDP
#   - name: rtsp-udp-6
#     port: 48106
#     protocol: UDP
#   - name: rtsp-udp-7
#     port: 48107
#     protocol: UDP
#   - name: rtsp-udp-8
#     port: 48108
#     protocol: UDP
#   - name: rtsp-udp-9
#     port: 48109
#     protocol: UDP
#   - name: rtsp-udp-10
#     port: 48110
#     protocol: UDP
#   - name: rtsp-udp-a-0
#     port: 48200
#     protocol: UDP
#   - name: rtsp-udp-a-1
#     port: 48201
#     protocol: UDP
#   - name: rtsp-udp-a-2
#     port: 48202
#     protocol: UDP
#   - name: rtsp-udp-a-3
#     port: 48203
#     protocol: UDP
#   - name: rtsp-udp-a-4
#     port: 48204
#     protocol: UDP
#   - name: rtsp-udp-a-5
#     port: 48205
#     protocol: UDP
#   - name: rtsp-udp-a-6
#     port: 48206
#     protocol: UDP
#   - name: rtsp-udp-a-7
#     port: 48207
#     protocol: UDP
#   - name: rtsp-udp-a-8
#     port: 48208
#     protocol: UDP
#   - name: rtsp-udp-a-9
#     port: 48209
#     protocol: UDP
#   - name: rtsp-udp-a-10
#     port: 48210
#     protocol: UDP
#   type: LoadBalancer