
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin-gaming
  namespace: kube-system
  labels:
    app.kubernetes.io/name: generic-device-plugin-gaming
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin-gaming
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin-gaming
    spec:
      priorityClassName: system-node-critical
      containers:
        - image: ghcr.io/squat/generic-device-plugin
          args:
            - --device
            - |
              name: uinput
              groups:
                - count: 10
                  paths:
                    - path: /dev/uinput
            - --device
            - |
              name: dri
              groups:
                - count: 10
                  paths:
                    - path: /dev/dri/renderD128
                    - path: /dev/dri/card1
            - --device
            - |
              name: kfd
              groups:
                - count: 1
                  paths:
                    - path: /dev/kfd
          name: generic-device-plugin-gaming
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
          # ports:
          #   - containerPort: 8080
          #     name: http
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
  updateStrategy:
    type: RollingUpdate