---
# yaml-language-server: $schema=https://github.com/games-on-whales/fenrir/raw/refs/heads/main/schemas/direwolf.games-on-whales.github.io/profile_v1alpha1.json
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: Profile
metadata:
  name: default
  namespace: direwolf-dev
spec:
  apps:
  - name: firefox
  - name: retroarch
  - name: steam
  - name: pegasus
  - name: lutris
  - name: prism-launcher
  - name: xfce
  - name: emulation-station
  - name: kodi
  # After you pair your device, you need to get the pairings crds, and place their name here, then apply.
  # This whill get you access to the applications in this profile
  # You can add as many devices as you want to a profile
  pairings:
  # Replace this with the results of `kubectl get pairings -n direwolf-dev`
  - name: "1ca62e79255d652d6e9cc84e24c9743d23916f34149d183473fd1b18e32a0de1"