apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: User
metadata:
  name: alex
  namespace: direwolf
spec:
  sessionResources:
    # This user can run apps up to the following limits.
    # appPolicy:
    #   requests:
    #     cpu: "4"
    #     memory: "8Gi"
    #     nvidia.com/gpu: "1"
    #   limits:
    #     cpu: "6"
    #     memory: "12Gi"
    #     nvidia.com/gpu: "1"

    # We are overriding the default resources for some sidecars for this user.
    sidecarPolicies:
      # You can specify which sidecars take which requests.
      # Give the streaming container gpu so it can use nvidia encoders.
      wolf:
        requests:
          nvidia.com/gpu: "1"
        limits:
          nvidia.com/gpu: "1"
