# This device class just relies on the defaults
# It will use /dev/dri/renderD128 for creating the wayland sessions
# You can always change it in accordance to your GPU render node
---
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: default-wolf
spec:
  selectors:
  - cel:
      expression: device.driver == "wolf.dra.io"
  config:
  - opaque:
      driver: wolf.dra.io
      parameters:
        video_settings:
          wayland_render_node: "/dev/dri/renderD128"
          runner_render_node: "/dev/dri/renderD128"
          video_producer_buffer_caps: "video/x-raw(memory:DMABuf), drm-format={NV12,YV12,YU12,P012,YUYV,YU24,AB24,AR24,XB24,XR24}"